### ISSUE TITLE
[Bug] Backup stuck on Android-System

### ISSUE THREAD

**Issue by legendofa** [machiav3lli/oandbackupx#167]
**Description**

The backup is stuck.

Android Notification: 1h

OAndBackupX:
Backup ... (2/213)
Android-System

**Steps To Reproduce**
1. Backup everything including data
2. No progress for over an hour

**Expected behavior**
A full backup of the system and apps is created.

**System Information(please complete the following information):**
 - Device: OnePlus 3T
 - Android Version: 10
 - ROM: LineageOS 17
 - App's Version: 3.2.0

Have not found any logfile but can provide it if someone knows where it is stored.

**Comment by Tiefkuehlpizze** [comment]
Hi, that's pretty easy:
You cannot backup "Android-System". It's a meta package and lets OABX backup the complete `/data` directory. You can call it a full system backup with all apps and their data. But OABX 3.2 is not able to handle pipes, symlinks and sockets, so it does not work. I cannot say, where it exactly is stuck.

The current development version doesn't show this item anymore, due to the fact, that it's a bad idea to do this kind of backup on a running system.

**Comment by legendofa** [comment]
Thanks, makes sense, now its running correctly.
