### ISSUE TITLE
[Feature Request] Consider adding support for older Android versions down to 6.0

### ISSUE THREAD

**Issue by Fs00** [machiav3lli/oandbackupx#171]
I was surprised to see that this app can run only on Android 8+ devices, which is a minimum supported release that leaves out ~40% of the Android user base (according to Android Studio distribution graph).
I would love to be able to use this app on some older devices that run Android 6/7 too.

I would be happy to contribute to the project to achieve the goal of supporting at least Android 6.
But before doing that, I'd like to know which were the reasons that led to such a high minimum version and which parts of the app are known to be incompatible with older Android versions.

Thank you!

**Comment by Tiefkuehlpizze** [comment]
Hi, it was decided to support Android 8+ to use a lot of the newer language features. There are currently 307 lines of code that are not compatible with older Android versions. The main issue is the Storage Access Framework, but also the Storage Stats and before Android 7 not even the stream function to process arrays and lists.

**Comment by Fs00** [comment]
Hmm... afaik Java streams and some other recent APIs can be used on every Android version since a few months ago (see https://developer.android.com/studio/write/java8-support#library-desugaring), so that shouldn't be a problem in theory.
Also, could you show me those 307 lines you mentioned? Out of curiosity :)

**Comment by machiav3lli** [comment]
Hi Fransesco, I already know of libDes, but it's not only the java8 support that's the problem here. The groups of deprecated classes and methods on each release makes it more complex to maintain the code in the future. 

Our focus for now is make the app fully compatible with storage access limitations of Android 11. Backward compatibility is at the end of the priorities' list, as it hardens the maintainability (very bad cost-performance ratio).

Should the app reach a stable state in the near future where backward compatibility as a "feature" has some priority, we would gladly work on it. But as it looks right now, minimum of Android 8 is more than enough to cover the needs of custom ROMs community (which is more or less the main targeted group of this project).

Let's keep the ticket open for a future possibility. Thanks.

**Comment by Fs00** [comment]
Thanks for your reply.
I agree with you on the importance of supporting newer Android versions and keeping the codebase as maintainable as possible in the long run.

I'm really interested in knowing which would be the pain points of making the app compatible, say, with Android 7. @Tiefkuehlpizze has already given some details, but I'd like to know more since I plan to do some investigation on my own to see if I can make the app target Android 7 without too much hassle and too many code changes.

Thank you!

**Comment by Fs00** [comment]
So... Assuming this won't happen, right?

**Comment by machiav3lli** [comment]
Yes, there's no indicator that adding support for older Android versions will get soon any easier.

**Comment by Unknown78** [comment]
> Should the app reach a stable state in the near future where backward compatibility as a "feature" has some priority, we would gladly work on it.

@machiav3lli, three years has passed, how about now?

**Comment by machiav3lli** [comment]
@Unknown78 nothing changed, I'd say it'd be more useless investment now than ever (less than 10% of devices are under A8, plus SU users are usually more up-to-date than common users)

**Comment by MrEngineerMind** [comment]
You can always use Titanium backup on devices that old.

**Comment by Unknown78** [comment]
That below 10% are still millions of users.
Apps are evolving and Titanium Backup won't do well with split .apk.
Fortunately, there's alternative such as Swift Backup.
