### ISSUE TITLE
[Bug] Back being restored on another device gives error "base.apk not found in backup"

### ISSUE THREAD

**Issue by devsk** [machiav3lli/oandbackupx#239]
**Description**
I created backup on my old device and copied the backup folder over to my new device. Restoring any app gives the error "base.apk not found in the backup" when the file is there. If the restore is done on the original device, it works fine.

**Steps To Reproduce**
1. Create backup on a device
2. Copy over the folder to another device
3. Restore an app
4. Error: base.apk not found in backup

**Expected behavior**
It should restore the app.

**Screenshots**

**System Information(please complete the following information):**
 - Device: Pixel 3XL
 - Android Version: R 
 - ROM: Stock
 - App's Version: 4.0.0

**Comment by devsk** [comment]
The file is there:
```
$ find OABackupX/com.skype.raider/
OABackupX/com.skype.raider/
OABackupX/com.skype.raider/2020-11-22-02-07-15-user_0
OABackupX/com.skype.raider/2020-11-22-02-07-15-user_0/data.tar.gz.enc
OABackupX/com.skype.raider/2020-11-22-02-07-15-user_0/external_files.tar.gz.enc
OABackupX/com.skype.raider/2020-11-22-02-07-15-user_0/base.apk
OABackupX/com.skype.raider/2020-11-22-02-07-15-user_0.properties
```

**Comment by ondro1030a** [comment]
Install skype manual from apk, then create again backup 2, and  replace files data.tar.gz.enc , external_files.tar.gz.enc  from your backup 1.
Look at file OABackupX/com.skype.raider/2020-11-22-02-07-15-user_0.properties
and 2020-****.properties in your new backup
there difference in path to apk and data.enc

**Comment by devsk** [comment]
Can't we account for this path change in the code? We know that its in one sub-folder down from the app folder.

**Comment by devsk** [comment]
I think I know the bug...:-) The backup folder path MUST match between the old and the new device.

Can't we store the relative path in the .properties file instead of storing the absolute path? That will make it so that we can use any path for backup and restore.

A use case is a system where internal storage may be precious and we want to use SD card instead.

Can we fix this please?

**Comment by machiav3lli** [comment]
Already fixed in the repo and test releases

**Comment by devsk** [comment]
How can I acquire a test release?

**Comment by Rolf-Smit** [comment]
I have the same question, do I need to build this myself?

I would suggest putting out a hotfix for this, anyone that downloads the latest release will have this problem. This is main functionality of the app if you ask me: create a backup on one phone and then move that to another.

**Comment by machiav3lli** [comment]
@Rolf-Smit it's not really a hot-fix, a hot-fix wouldn't cause a uncompatibility with the directly earlier release, this is a design update and it's a part of huge changes that are underway. Otherwise since 4.0.0 the app was migrated from Java to Kotlin. A stable release will have to wait.

**Comment by machiav3lli** [comment]
@devsk @Rolf-Smit as mentioned in the README the test versions are released and discussed in the groups on Telegram and Matrix

**Comment by Rolf-Smit** [comment]
@machiav3lli I totally get that this is not a hot-fix release.

However the current version available on F-droid is basically broken, you can't create a backup on device A and restore it on device B due to this bug (unless you fix the path's yourself in the files). So I just wanted to point out that it could be a good idea to make a fix for that specific build, so that people that download the app from F-droid can at least use it to backup on device A and restore it on device B. Or would fixing that break compatibility with older versions? If so, is that more important than having a working version?

**Comment by machiav3lli** [comment]
It's not true that the restore on device B isn't possible, it just has to have the same address as the one in which the backup was done on device A. 

And yeah, it's important to have a new stable release instead of forcing people to do clean backups each and every week. As the app's statement says, the app is under heavy development and this is for the people doing the test to take, not every user have/want to do it. We're already in the 10th alpha release.

**Comment by devsk** [comment]
Is it possible to put one of these test builds here on github with a alpha/beta tag weekly? I avoid most of the social media for a good reason. Please consider making weekly alpha releases on github if the stable version is very far away.

**Comment by b16r05** [comment]
Workaround: https://forum.xda-developers.com/t/app-8-0-open-source-root-oandbackupx-apps-and-data-backup-tool-for-android.4167179/post-84203735

**Comment by Massimo-B** [comment]
I thought this issue is fixed long ago. I got a
```
RestoreAppAction$RestoreFailedException:
base.apk is missing in backup
```
I have transferred a complete backup directory tree from some Xiaomi MIUI 14, Neo-Backup 8.3.12, to OxygenOS 15.
Restoring to Xiaomi HyperOS2 worked with the same directory tree.
