### ISSUE TITLE
[Feature Request] How decrypt data.tar.gz.enc?

### ISSUE THREAD

**Issue by gcoimbra** [machiav3lli/oandbackupx#257]
**Is your feature request related to a problem? Please describe.**
I need to decrypt the data outside the app. I have the password

 - App's Version: 
lastest on fdroid

**Comment by gcoimbra** [comment]
The app is failing to decrypt it. And I need  the data before a patch can be released...

**Comment by machiav3lli** [comment]
Check the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md)

**Comment by morfikov** [comment]
@machiav3lli I also had the same question, but it looks like the FAQ is outdated -- the link is wrong and also there's no `app/src/main/java/com/machiav3lli/backup/handler/Crypto.kt` file. 

I think someone should write a HOWTO on how to access the encrypted backup data under linux. To be honest, I don't encrypt the backup data, just because I have no idea how to decrypt it under my Debian.

**Comment by machiav3lli** [comment]
Actually I fixed the link to the encryption setup couple of days ago (but maybe not the text).

Yeah a howto could also be a nice addition later.
