### ISSUE TITLE
OpenPGP support

### ISSUE THREAD

**Issue by mase76** [machiav3lli/oandbackupx#33]
Do you plan to bring back the support of OpenPGP encryption with Openkeychain?

**Comment by machiav3lli** [comment]
Nope, the app managing OpenPGP for android is not being maintained actively and therefore it's not logical to implement it back, when there's already the AES in-app encryption solution.

**Comment by mddvul22** [comment]
Openkeychain version 5.5 was just released in January.  Works great in the older oandbackup app.  Please reconsider.  It is an open standard that is very versatile.

**Comment by mase76** [comment]
This would also make it possible to decrypt on PC.

**Comment by machiav3lli** [comment]
@mase76 this is already possible through the current implementation.

**Comment by machiav3lli** [comment]
@mddvul22 it doesn't make much sense, using a plug-in while there's already an in-app solution. But I'll reconsider this, when I start rewriting the app's core structure.

**Comment by mase76** [comment]
What tool to use for decryption (on Linux)?

**Comment by machiav3lli** [comment]
@mase76 7z x myZip -pMYPW, which is also supported by most of archives' managers (Ark, Xarchiver etc.)

**Comment by mddvul22** [comment]
Thank you for reconsidering!  I much prefer the .gpg format.  And one less password to keep track of, when using openkeychain.

**Comment by mase76** [comment]
I was not able to decrypt on Linux with 7z or xarchiver.

**Comment by Tiefkuehlpizze** [comment]
You cannot simply decrypt and extract the data. The `.aes` suffix is a marker, that the file is encrypted using AES and it's pure byte garbage if you don't know that. I'm sure, there is an application out there, that can reverse OABX's crypto using the password.

If someone wants to implement something, all you need is in [Crypto.java](https://github.com/machiav3lli/oandbackupx/blob/master/app/src/main/java/com/machiav3lli/backup/handler/Crypto.java#L112).

I know, this is not a satisfying answer, but adding pgp support seems to me like a good chunk of work. 
The original OAB implementation can be used as reference, but I would offer it as alternative to the current crypto solution due to the fact, that pgp needs the completed backup and writes the encrypted contents in a new file.

The current crypto solution handles encryption and decryption on the fly. The big advantage is, that sensitive material is never stored unencrypted on insecure storage such as the external storage (and it's obviously faster with a growing amount of data - probably a few hundred milliseconds, but it sums of in batch processing)

**Comment by mase76** [comment]
I'd like to have a tool, even in Java, to decrypt the data outside of Android.

**Comment by jursed** [comment]
I might be missing something here, but the obvious problem with using (only) symmetric cryptography like AES is making the encrypted backups automated (without having to type out the encryption key every time). Equivalently, it is the problem of securely and persistently storing the encryption key on the device. If the key is stored in plaintext and an adversary gains access to the unlocked phone, that will give them access to any historic backups it contains (in addition to having access to all other current data on the phone, admittedly.)

Hybrid cryptosystems (like what OpenPGP can provide) solve that issue.

That said, integrating with Openkeychain might (?) still be overkill, especially without the possibility to stream the backup encryption process (re [@Tiefkuehlpizze](https://github.com/machiav3lli/oandbackupx/issues/33#issuecomment-684050777)). Is it difficult to emulate the OpenPGP's functionality using only Android's own API? (Meaning: generate new, random data-encryption (AES) keys for every new backup, and then encrypt those keys with the user's public (e.g. RSA) key. I know nothing about Android, mind.)
