### ISSUE TITLE
[Feature Request] Playstore release

### ISSUE THREAD

**Issue by Taknok** [machiav3lli/oandbackupx#340]
Is there a playstore release planned ?

A playstore release would easier update of the app.

**Comment by machiav3lli** [comment]
I have no plan for a play store release. But maybe soon enough on Aptoide.
Till then FDroid & GH are the only ways.

**Comment by MartinX3** [comment]
@machiav3lli 
Wouldn't it possible to automate playstore releases via github actions? If that's the problem preventing playstore releases.

**Comment by machiav3lli** [comment]
It's not about automation, it's about the ethic and freedom in F(L)OSS. I won't publish the app on a proprietary store and more specifically on Play Store. At the same time I don't see why the users shouldn't use FDroid, if they want an open-source backup tool.

**Comment by MartinX3** [comment]
@machiav3lli I use F-Droid as well
And yes, people using backup solutions requiring root would also know how to install F-Droid, the #1 Open Source Store (but also hosting closed source apps)

Just in my case the auto updater is not reliable.
Either it forgets to autoupdate, or i need to manually press "update" on the apps or it fails to install the update because of some mismatch and I need to redo the update search and apply it then.

But I think the main advantage is about saving one app from your phone, if you only use F-Droid because of OAndBackup.

PS: I will remove the other backup apps and migrate to this app today because it is open source.
I like your good job maintaining it.

**Comment by MartinX3** [comment]
For the record
Fdroid should become better at updating apps in the future
https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/

**Comment by machiav3lli** [comment]
If you're having problems with privileged FDroid, maybe you can use [Aurora Droid](https://f-droid.org/repo/com.aurora.adroid) with root installation method. This is more reliable and reacher on features, but still not that stable.

**Comment by MartinX3** [comment]
It's just that the Fdroid way a workaround until the new A12 change (Which will work with APPs compiled for A10) I need to install via recovery (on every update, since it doesn't use addon.d)

Ah, thanks for the aurora store. I give it a try. :)
