### ISSUE TITLE
[Bug]Could not check "Exclude system apps"

### ISSUE THREAD

**Issue by freemannhp** [machiav3lli/oandbackupx#358]
**Description**
When creating a schedule of backuping "New and updated apps”, the box of "Exclude system apps" could not stay checked after the schedule is saved.

**System Information(please complete the following information):**

- Device: OnePlus 7t
- Android Version: a1q
- ROM: (AOSP, MIUI, OOS...)  pixel experience
- App's Version: 6.0

-----------------------------

**Additional Notes**

* If you're on the latest Test version(from the TG-Channel or Matrix-Room) please report there directly, not here.

* If you're on the latest github version:
  
  * Please read the [FAQ](https://github.com/machiav3lli/oandbackupx/blob/master/FAQ.md) first.
  * Please read all the open Issues. If one does match yours, leave a comment there if there's some extra information you can provide.

* If you're not on the latest github version. Update, then make sure that the bug is still there. If it's go further with reporting.

Thanks for reporting.

**Comment by machiav3lli** [comment]
Yeah, seems so. Thanks for reporting will fix soon enough.

**Comment by Switch123456789** [comment]
I think it would give a much better UX if you would just have to enable/disable (checkbox) certain filters instead of using this weird hybrid approach where "system apps" appears twice.

Like this:

[ ] Include system apps
[ ] Include user apps
[ ] Include special backups

[ ] Only updated apps
[ ] Only visible apps
