### ISSUE TITLE
I cannot restore my encrypted backups from another device

### ISSUE THREAD

**Issue by anedroid** [machiav3lli/oandbackupx#371]
**Description**
I am sure that password is good, but I get error when I try to restore backups from previous device. Because that, I must start from begin. Backups always should have possibility to migration. If I copy content of /data/data/com.machiav3lli.backup to another installation, app suddenly crashes, probably because using keystore. I am frustrated, I must spend much of my free time signing in again in apps, restoring contacts, calendar, notes, changing settings, etc. Some things I can't restore, e.g. games.

**Steps To Reproduce**

1. Create encrypted backup of any app data
2. Move backup directory to another device
3. Install OABX, set backup dir on existing one
4. Install app which data you want to restore
5. Error: Could not read the input file or write an output file due to IOException: java.io.Exception: Input is not in the .gz format

**Expected behavior**
App should ask for password (no if you set same password in settings before), decrypt files, extract, and put them in the right places.

**Screenshots**
![Screenshot_20210620-174237_OAndBackupX](https://user-images.githubusercontent.com/72965850/122680411-4631f480-d1ef-11eb-88e8-ed3c2730a69f.png)

**System Information**

- Device: Moto g7 Power
- Android Version: 11
- ROM: (AOSP, MIUI, OOS...)  LineageOS
- App's Version: 6.0.1

**Comment by machiav3lli** [comment]
First point: the data(data/data/com.machiav3lli.backup) of OABX can't be moved between setups, as the sensetive parts (i.e. encryption password) is encrypted using android's KeyStore (device-generated encryption key).
Now to the problem: thr message of the exception points out, that you're trying to restore a not encrypted files. Which would imply that you've encryption turned off or the backup itself is a mix of a properties file that says it's not encrypted and data tars that are.

Some extra information that can help:
- What is your backup directory and Is it on an sd-card/otg maybe?
- Are the backups made by the original device created with the same version, or some older ones?
- What is the arch of the SoC of the original device? Is it the same for both devices?

**Comment by mwelsch** [comment]
Having the same error message. In my case the apps I wanted to restore installed fine, however the data cannot be restored.

I guess apk files are not encrypted and only data is encrypted, and after copying to a new device oandbackupx tries to restore the data from the `.enc` file, without taking the file extension into account.
![image](https://user-images.githubusercontent.com/31733941/122818291-4b6b6e00-d2d9-11eb-893e-9170f74d7a52.png)

Since the encryption password is stored in android's Keystore I guess I have no way of retreiving the data after cleanly wiping my old ROM? Also why not use the password directly as encryption key? I was kinda expecting the app to use a straight forward symmetric encryption with my password as the only part needed to decrypt stuff

**Comment by adamsmd** [comment]
I was also hit by this, and it also turned out to be me putting in the wrong password.  Is there maybe some way to check if the password is correct and generate an error message specifically for incorrect passwords?

**Comment by machiav3lli** [comment]
@adamsmd it's already done in the latest test builds, tjis is why I closed it
