### ISSUE TITLE
[Bug] Restoring data fails

### ISSUE THREAD

**Issue by murchu27** [machiav3lli/oandbackupx#437]
**Description**
When trying to restore data on my OnePlus Nord CE 5G (EU version, Oxygen OS build number 11.0.11.11), every app fails with an error like below:

```
Aegis: a: Could not restore a file due to a failed root command: ls: /data/user/0/com.beemdevelopment.aegis: No such file or directory
```

This data was originally backed up when running LineageOS 17.1. I have restored successfully multiple times with LineageOS installed, but now that I have installed OxygenOS, OAndBackupX is failing to restore data. APKs are restored without issue.

**Steps To Reproduce**

1. Back up apps and data on LineageOS 17.1
2. Restore device to OxygenOS 11.0.11.11, unlock bootloader and root device
3. Try to restore apps with OAndBackupX
4. Restoring APKs works, but restoring data shows the above error.

**Expected behavior**
OAndBackupX should successfully restore data.

**System Information**

- Device: OnePlus Nord CE 5G
- Android Version: 11
- ROM: Oxygen OS build 11.0.11.11.EB13BA
- App's Version: 7.0.0

**Comment by murchu27** [comment]
Seems like this was a false alarm. I tried again later, and restoring data worked without issue...

**Comment by mimmiechan** [comment]
I had the same or a similar issue. Rebooting helped. I tried to restore Gboard data from another rom.
`Gboard: a: Could not restore a file due to a failed root command: ls: /data/user/0/com.machiv3lli.backup/cache/restore_[a long string]/cache': Directory not empty`

Android 11 Sakura 5.2 rom based on LineageOS. Galaxy S8 exynos dreamlte. Magisk latest version.
