### ISSUE TITLE
Set permissions on backup folder to root only

### ISSUE THREAD

**Issue by gcoimbra** [machiav3lli/oandbackupx#77]
Some apps, like WhatsApp, store database keys in their data directory. By using OAndBackup, without encryption, these keys will be placed in general storage that many apps have access to. 

A suggested change will be set root permissions on the backup folder. Since the user already has root permission for some apps, they'll be able to use the files anyway? 
If this doesn't work, maybe use encryption as default and warn the user of this issue?

**Comment by Tiefkuehlpizze** [comment]
Hi, that's a good point, people really might not be aware of. There are apps that use Android Keystore like AVM FritzFon (a VoIP telephony app for FritzBox routers by AVM). Because the design of Android Keystore never hands out the key material, it's not possible to extract these keys. I would expect, that if you would try to copy the file with root permissions, you'll find your device in a bootloop after a restoring it after a factory reset. So there is lots of effort needed, to have a proper way of handling this. But this is not the topic here. :smiley: 

Setting encryption by default opens the problem what passphrase we use. We could force the user to set one, which would also be handy when restoring data after a factory reset. But since it can also mean the risk of a data loss because users are users and forget passphrases and we cannot offer a restoring mechanism, I wouldn't force it.

Your second idea, to lock the directory to root only does not work, because sdcards are mounted using sdcardfs filesystem which does not support file permissions and falls back to a userid and groupid specified in the mount options to be compatible with the filesystem representation of Linux.
And a second thing: OAndBackupX does not always use root permissions to write into the backup archive. Actually it's only used to copy the data from the system managed directory to the backup directory and then the app can compress and encrypt it. There's another weakpoint where an attack could retrieve the original cleartext data from the raw filesystem.

This is definitely an important point, but on my personal list, making the app round and user friendly comes after some technical topics.

**Comment by gcoimbra** [comment]
So maybe just warn the user to use encryption?

**Comment by machiav3lli** [comment]
Already fixed in my local repo. Will push when I have time to. Thanks for the feed back
