### ISSUE TITLE
Compatibility with oandbackup

### ISSUE THREAD

**Issue by farfromrefug** [machiav3lli/oandbackupx#9]
I need to backup restore feom KitKat to Oero. 
So I would need to use oandbackup to backup and yours to restore.
Would that work?
Or maybe you can lower the minsdk?

**Comment by machiav3lli** [comment]
Unfortunatly lowering the minSDK isn't possible after this structural change. 

Cross-Restoring from oandbackup works fine on 0.9.3. after that I did add the protected data backup and didn't test the cross-restoring. But you're encoureged to try and test it if you'd be doing this reguarly. Otherwise just use 0.9.3 to restore, then update to latest

**Comment by farfromrefug** [comment]
Perfect will try with 0.9.3 and report
