### ISSUE TITLE
[Bug] Unclear backupable objects

### ISSUE THREAD

**Issue by DamienCassou** [machiav3lli/oandbackupx#91]
![oandbackupx-packages](https://user-images.githubusercontent.com/217543/90331104-7054cd80-dfb2-11ea-8b7b-8b1a0b3049e8.png)

In my opinion, these 5 screenshots of the application show the same concept: "backupable objects". Nevertheless, the application shows them in 5 different ways. I think it's quite confusing. For example, "Android System" is not visible in the "Custom list" screenshot above.

I think what the application misses is the concept of backupable object which would be centered around the user instead of the system. For example, I would expect these elements to be backupable objects:
- Phone call journal
- Sound settings
- Wifi access points

Also, each of my apps (e.g., k-9 mail, Element) would add 2 items to the list of backupable objects:
- k-9 mail package
- k-9 mail data
- Element package
- Element data

Then, these backupable objects could be ordered in 3 different categories:
- System settings
- Application data
- Application packages

To decide what to backup, the user would be able to select either individual backupable objects or whole categories.

**Comment by Tiefkuehlpizze** [comment]
Hi, thanks for this interesting idea.
The inconsistencies you've highlighted are resident in the code as well. At least between Batch and Single Backup activity it's easy to see, that there is a lot duplicated logic or at least idea.

I'm currently working on some bigger refactoring where I'm replacing the bloated `AppInfo` as universal object. It became a lot more complicated when I introduced multiple backups per app and it made clear, that `AppInfo` combined meta information, backup information and even UI information in a single object.
The single backup implementation of `AppInfo` might be some inspiration for your _package and data_ idea, because it only knows about 4 states: No backup, data, app or both and the last backup done sets this value. So even if the app would have a data backup from a past backup, it wouldn't offer it anymore when there was an app only backup afterwards.
I like the combination of app and data together, because I can make sure, that the right versions are together.

The system settings are already present as "Special Backups". I've seen more interesting files to backup. I wrote a little bit more about what special backups are and how they work on your issue #88, but for everyone interested you can read my comment [here](https://github.com/machiav3lli/oandbackupx/issues/88#issuecomment-674497616).

I haven't looked into call history and sms backups yet, but there are several people asking for it. Maybe it'll be caught up on a later point of time.

Some other interesting things are system settings stored in a database. This would be another special case of settings. I wouldn't backup and restore the whole database for sure. That could - again - to broken systems. But definitely a field to explore.

**Comment by machiav3lli** [comment]
Seperation of "Backupable objects" could result a more unstable experience with the mixture of app-data of different versions. That's why am glad that @Tiefkuehlpizze has taken the other way keeping themmore connected.
Having different Items for different functionalities even when the backend item is the same isn't per se a bad practice.
The same here applies as in #90, I'm already thinking of redesign which is to a certain degree already reflected in the DevDoc, but first I'll be waiting for the all new AppInfo(X), so I don't have to do everything twice.
