### ISSUE TITLE
[Bug] Scheduled backup frozen

### ISSUE THREAD

**Issue by DamienCassou** [machiav3lli/oandbackupx#92]
**Description**

The nightly backup froze at "Backing up... (63/152) Element (Riot.im)"

**System Information(please complete the following information):**

-    Device: OnePlus 1 (bacon)
-    Android Version: 9
-    ROM: LineageOS (July 23rd)
-    App's Version: 3.0.0 from f-droid

**Comment by darhma** [comment]
For me the backup of Element doesn't work. See #45 and #84

**Comment by machiav3lli** [comment]
The error follows #84.
For the future, a rule of thumb applies: if a scheduled backup get hung up on an app, this means that the app (and its data) are the ones facing an error.
Otherwise I'll be reworking how errors get handled in scheduled/batch backups as soon as the new backup logic is ready, so it doesn't stop but report failure at the end.

**Comment by mase76** [comment]
I have this freezes with random apps, but mostly big ones. A manual backup of these works.
