### ISSUE TITLE
[Feature Request] Backup/Restore app permissions

### ISSUE THREAD

**Issue by hagaygo** [machiav3lli/oandbackupx#93]
Hi

When restoring apps the permissions of the restored app is reseted.

Some apps re-ask for the permissions when we run them, some does not and we need to manually add them via app info.

Some apps runs on the background so if we don't add those permission s they don't work properly and we only fix the permissions after we notice that.

Thanks for the maintenance of this app.

**Comment by machiav3lli** [comment]
As far I know, such a functionality needs system-level permissions or could be done from the recovery. Should any solution come up, I'll implement it, but till then it's unforunately not possible

**Comment by hagaygo** [comment]
The app has root access, is it not enough ?

**Comment by Tiefkuehlpizze** [comment]
As non-privileged app, you have absolutely no chance to do that via API. But we could manipulate the `appops.xml` file if we understand how it works. But it's a bit cryptic.

**Comment by Atrate** [comment]
This should really come in handy regarding AppOps, @Tiefkuehlpizze https://muntashirakon.github.io/AppManager/tech/AppOps.html#appops-xml

**Comment by bengalih** [comment]
I'll second this is a major issue, although I'm pretty sure it existed in TiBu and also for restores from Google drive as well.
As mentioned it seems to be more problematic from a restore.  Usually, when you install an app clean it will prompt you on first run for the permissions required.  But, an app restored from backup doesn't usually do this and often creates weird issues.  I can tell you many times I reinstalled Hangouts and it didn't have permissions to my contacts and never prompted me so I wasn't seeing names.  Another example is an app which requires an external download (OBB data) and yet is somehow restricted from storage access...app will usually crash and you will think it is just a bad backup/restore.

Short of implementing a solution to restore the permissions, would it at least be possible to *record* those permissions prior to backup and perhaps present a report after restore to warn us what permissions to set back up?  This would really be a huge improvement to the way things work in the past and would be a killer feature, even if it was manual.  TBH, I'm sure there are some other apps out there which can give you a permissions report, but I haven't found a great one that isn't overburdened with too much other junk rather than just the 10 or so basic permissions (storage, location, draw over apps, device admin, etc..).

**Comment by hagaygo** [comment]
I see this issue is closed now , is this means the feature is in the latest version ?

I tried a backup of a simple application with storage access , uninstalled it and restored via oandbackupx 5 , app got restored fine , but without storage permissions.

**Comment by machiav3lli** [comment]
@hagaygo Settings > Advanced settings > restore with all permissions

**Comment by hagaygo** [comment]
After i saw your response , I immediately  wondered "Why its not "ON" by default ?".

Tested on my "test case" with the this option on , and can verify its indeed set the permission on.

But, (of course there is a "but" :) ) I understand this implementation give the restored app all the permissions the app asks for, While if before i make a backup i had an app with access to storage , but without access to location or contacts  , after restoring , the app will have access to all 3.

While of course its "better than nothing" , I believe its far from ideal solution (Please correct me if i am missing something).

Currently the "only" missing  functionality is to store the  the "active permissions" only , and when restoring enable only those permissions. (While it sounds simple  , it might require some hidden API , but as mentioned in this thread, its possible).

Just in case my response might be read/sound as ungrateful, Many Thanks for all your efforts.

**Comment by machiav3lli** [comment]
Nah it's all right. On the "default on" topic, it's because I don't want to give apps more permissions than they originally have. With this we come to the second point, and it's all true, but I chose this way, as I didn't want to change the backups' structure while I've been in beta and not having enough time to invest into the problem right now. It'll be reiterated on in later major releases, but that's not on the top of my list for now. Thanks.

**Comment by Practicalbutterfly5** [comment]
I believe that this is an essential feature for a backup app. [This stackoverflow answer](https://stackoverflow.com/a/37294804) shows how to get currently enabled permission of an app. These permissions could be stored in a file and restored using `pm grant package_name permission_name`
