### ISSUE TITLE
[Bug] Restore does not work: Errors Occurred: RestoreFailedException: IOException

### ISSUE THREAD

**Issue by baack** [machiav3lli/oandbackupx#98]
**Description**
Restore function does not work at all for all applications on Android 10 (LineageOS 17.1).
Each time I try to restore APK+Data or Data I get a message:
`Errors Occurred`
`RestoreFailedException: IOException`
And no more details.

**Steps To Reproduce**
1. Make backup (I made on Android 8.1 LineageOS if it's important).
2. Try to recover APK+Data for application from this backup (I tried on Android 10 LineageOS 17.1)
3. Application shows message with title "Errors Occurred" and text body: "RestoreFailedException: IOException"

**Expected behavior**
Application is restored in the state of backup.

**System Information(please complete the following information):**
 - Device: Android phone
 - Android Version: 10
 - ROM: LOS (LineageOS 17.1), latest Magisk installed.
 - App's Version: 3.1.0 and 3.0.0, the same.

-------------------------------
**Additional Notes**
Searched for this message text or title and found no similar issues by other people.
The App version is up to date, installed from F-Droid.
The problem here is not only that I can not restore applications but the whole exception handling is a bit poor, IOException provides not enough information. Maybe there is a way to get real message of this IOException to get more information? Some kind of logs?

**Comment by Tiefkuehlpizze** [comment]
Hi, I agree, the exception handling still needs to be improved. 

We had a similar issue on the Telegram channel. Can you check, if your backup is encrypted and you have set the password before restoring.
You can also keep track of logcat, if you want to see some details. It might be helpful.

**Comment by baack** [comment]
>Hi, I agree, the exception handling still needs to be improved.

Maybe add to text body exception.Message or something like that? To know what operation on what file failed.

>Can you check, if your backup is encrypted and you have set the password before restoring.

No, I don't use passwords for backup or backup directory. 

>You can also keep track of logcat, if you want to see some details. It might be helpful.

Any information how to use logcat in this case? I installed logcat viewer from f-droid but saw nothing in log about oandbackupx.

**Comment by baack** [comment]
And additional note: if I try to recover apk+data than I get this error message but application gets installed (apk) but with default data. So, the real bug is about restore of data.

**Comment by baack** [comment]
I installed Android 9 (LineageOS 16.0) and restore give the same error.

I played with the directories a bit and faced several other problems (everything bellow is from Android 9)
:
* Backup is not working from sdcard (fat32 formated). The error message is: `BackupFailedException: Could not create data backup directory: /storage/1234-5678/OABXtestpoco/com.applicationname/data`. It's probably a bug, because app has all permissions, runs with root and the directory /storage/1234-5678/OABXtestpoco/ does exist (and is chosen in settings).

* Restore is not working from internal memory (I copied backup from sdcard to internal memory to avoid bug with bad work with sdcard). The message now has more information:
`RestoreFailedException: mv: /data/user/0/com.appicationname/lib: Too many symbolic links encountered.`

What? What are those symbolic links?

PS.  Another bug - the Last backup parameter shows something strange, like almost current time, or sometime it's 1970 year (zero, start of Unix time). I understand OAndBackupX has BETA status, but please make it great as application is a must-have tool for backup and the only semi-working F/LOSS solution for modern Androids.

**Comment by Tiefkuehlpizze** [comment]
> Maybe add to text body exception.Message or something like that? To know what operation on what file failed.

I rewrote the whole backup/restore logic to allow the UI. To keep things easy to process, it's always a `BackupFailedException` or `RestoreFailedException` that can exactly say what's wrong because it was thrown because the app detected some issue. But these exception can also wrap another exception like the `IOException`. From a programmers point of view, the UI cannot recover from `IOException`, so it gets wrapped and eventually stuffed with more information about the circumstances, so the UI/Worker Thread can decide what to do.
When I implemented this, I stopped at the point when I got too much in touch with the UI, to finish a milestone and just release it.

> And additional note: if I try to recover apk+data than I get this error message but application gets installed (apk) but with default data. So, the real bug is about restore of data.

Yes, the first step is to install the app again. Then the data can be restored. I'm still unclear about how to handle an inconsistent state. In this case, it doesn't harm too much. 

>     * Backup is not working from sdcard (fat32 formated). The error message is: `BackupFailedException: Could not create data backup directory: /storage/1234-5678/OABXtestpoco/com.applicationname/data`. It's probably a bug, because app has all permissions, runs with root and the directory /storage/1234-5678/OABXtestpoco/ does exist (and is chosen in settings).

Yes, you cannot select anything else than the internal storage. In best case, you just don't touch this option for now. Android became very restrictive on file system access because of privacy.
 
>     * Restore is not working from internal memory (I copied backup from sdcard to internal memory to avoid bug with bad work with sdcard). The message now has more information:
>       `RestoreFailedException: mv: /data/user/0/com.appicationname/lib: Too many symbolic links encountered.`
> 
> What? What are those symbolic links?

This seems to be interesting. the `lib` directory is a _symbolic_ link that references another directory. It's common on unix systems like Android to use it.
Symbolic links are special files that OABX cannot backup. The lib folder is a special one, that is always in place and doesn't add any value for backups. That's why OABX is ignoring it.
I'm curious why the restore functionality has issues now.


> PS. Another bug - the Last backup parameter shows something strange, like almost current time, or sometime it's 1970 year (zero, start of Unix time). 

If it's 1970, the backup only partially created and was interrupted. You should simply delete it and only check the raw data out, if you desperately need to restore something.

> I understand OAndBackupX has BETA status, but please make it great as application is a must-have tool for backup and the only semi-working F/LOSS solution for modern Androids.

Thanks, I appreciate the good feedback and all I can do is urging for patience. The project has only two active developers with their private lives and interests. There's a lot to do in the app and you can see all the open issues with valuable feedback. Some of the cool features and ideas might need to wait for some time, because the focus is still to get out of that _not-even-beta_ feeling and become reliable and stable.

**Comment by baack** [comment]
> Yes, you cannot select anything else than the internal storage. In best case, you just don't touch this option for now. Android became very restrictive on file system access because of privacy.

Wow, I see. It's quite unclear and a lot of users can face this, who has sdcard. It's convenient to use sdcard for transfering backup especially from one phone to another. Maybe app should check path for storage/sdcard location and prompt about internal memory requirement.

I tried again restoring applications that are not installed on the phone from internal memory backup from different phone and it started to work for some reason! No warning during restore and both apk+data seems to be restored properly. I don't actually know what changed as I use the same backup folder from sdcard copied to internal memory.

**Comment by baack** [comment]
About the time, when it's not 1970, it's a modification time of the directory in the backup, isn't it? If it is then I understand the problem in my case - the standard application Files copies the backup dictory with setting the current time as modification time, that's why it's different than actual one. So, maybe keeping actual date in the xml can be better as it will allow to remove dependence on filesystem attributes.

**Comment by Tiefkuehlpizze** [comment]
> Wow, I see. It's quite unclear and a lot of users can face this, who has sdcard. It's convenient to use sdcard for transfering backup especially from one phone to another. Maybe app should check path for storage/sdcard location and prompt about internal memory requirement.

I'm already working on another huge change, that hopefully doesn't require this and implements storage like Android is expecting it. :) 

> About the time, when it's not 1970, it's a modification time of the directory in the backup, isn't it? If it is then I understand the problem in my case - the standard application Files copies the backup dictory with setting the current time as modification time, that's why it's different than actual one. So, maybe keeping actual date in the xml can be better as it will allow to remove dependence on filesystem attributes.

As far as I can remember it's missing the "log" file in the backup directory and falls back to this value. I would suggest to remove backup leftovers if a backup job failed to avoid considering this as a valid backup at all.
